### ISSUE TITLE
Pod doesn't start without a label

### ISSUE THREAD

**Issue by ThetaDR** [networkservicemesh/cmd-admission-webhook-k8s#148]
Steps to reproduce:
1. Start Nsm
2. Create alpine.yaml like this one
```apiVersion: v1
kind: Pod
metadata:
  name: alpine-1
  namespace: default
  annotations:
    networkservicemesh.io: "kernel://my-vl3-network/nsm-1"
spec:
  containers:
  - image: python:3-alpine
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    name: alpine
  restartPolicy: Always
```
3. Apply it. 

You should get an error:
`Error from server (InternalError): error when creating "alpine.yaml": Internal error occurred: failed calling webhook "[admission-webhook-k8s-898d775b5-h588g.networkservicemesh.io](http://admission-webhook-k8s-898d775b5-h588g.networkservicemesh.io/)": failed to call webhook: an error on the server ("unknown") has prevented the request from succeeding`

**Comment by denis-tingaikin** [comment]
Resolved by https://github.com/networkservicemesh/cmd-admission-webhook-k8s/pull/147

Please check latest version of application and be free to reopen issue if it is still reproduciable.
