### ISSUE TITLE
Feature Request: Allow configuration of initContainer resource requests and limits

### ISSUE THREAD

**Issue by trastle** [networkservicemesh/cmd-admission-webhook-k8s#292]
In our environment we require user namespaces to specify requests and limits for containers.
We enforce this with policy in the cluster.

When the webhook injects the NSM init container into a PodSpec no resources and limits are specified.
See: https://github.com/networkservicemesh/cmd-admission-webhook-k8s/blob/main/main.go#L254 

We would like to be able to configure the requests and limits on the init container so we can set them in a way that complies with our policy requirements.

**Comment by edwarnicke** [comment]
@trastle How would you like that injection to look?

**Comment by denis-tingaikin** [comment]
@edwarnicke , @trastle I think we could simply add a few new envs into webhook configuration with default limits. 

Does it sound good for ypu?

**Comment by denis-tingaikin** [comment]
Hello @trastle,
 
 We've added evns for configuring limits. See at  https://github.com/networkservicemesh/deployments-k8s/pull/9727/files
 
 Feel free to reopen the ticket if we missed something.
